version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ULTRAVOX_API_KEY=${ULTRAVOX_API_KEY}
      - ULTRAVOX_API_URL=${ULTRAVOX_API_URL}
      - SERVICE_URL=http://localhost:3000
      - PORT=3000
      - BATCH_SIZE=50
      - SCHEDULE_INTERVAL=30
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=call_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: